Changes in tests

diff --git a/spark/src/test/resources/docker/scripts/run b/spark/src/test/resources/docker/scripts/run
--- a/spark/src/test/resources/docker/scripts/run
+++ b/spark/src/test/resources/docker/scripts/run
@@ -1,6 +1,19 @@
 #!/bin/bash
 set -e
 
+PROJDIR="$1"
+shift
+
+if [ "$PROJDIR" = "" ]; then
+  echo "Usage: $0 project-directory" 1>&2
+  exit 255
+fi
+
+if [ ! -d "$PROJDIR" ]; then
+  echo "$PROJDIR not found" 1>&2
+  exit 255
+fi
+
 docker ps | grep -q "\<master\>" || docker run -d -p 8080 -h master --name master test_spark/master
 sleep 5
 
@@ -8,7 +21,7 @@ for i in $(seq 1 3); do
   docker ps | grep -q "\<slave$i\>" || docker run -d -p 8080 -h "slave$i" --name "slave$i" --link master:master test_spark/slave
 done
 
-docker run -d -h "sbt" --name "sbt" --link master:master $(for i in $(seq 1 3); do echo " --link slave${i}:slave$i"; done) -v "$(cd "$(dirname "$0")/../../../../../.."; pwd):/ammonite-shell" test_spark/sbt
+docker run -d -h "sbt" --name "sbt" --link master:master $(for i in $(seq 1 3); do echo " --link slave${i}:slave$i"; done) -v "$(cd "$PROJDIR"; pwd):/project" test_spark/sbt
 sleep 5
 
 HOSTS="$(docker exec -it sbt cat /etc/hosts | grep -E '\<master\>|\<slave[1-3]\>|\<sbt\>')"
@@ -17,4 +30,4 @@ for i in $(seq 1 3); do
   docker exec "slave$i" /bin/bash -c "echo \"$HOSTS\" >> /etc/hosts"
 done
 
-docker exec -it sbt sbt ++2.10.4 "spark/test:run-main ammonite.shell.Main --class-wrap"
+docker exec -it sbt sbt "$@"
